apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  # Namespace should NOT be specified on PersistentVolume; it's a cluster-level resource.
spec:
  accessModes:
    - ReadWriteOnce
  capacity: 
    storage: 5Gi
  hostPath: 
    path: /data
